server:
  port: 8181

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_demo?serverTimezone=UTC
    username: root
    password: 123456
    #数据库连接池配置
    #初始化链接数
    initialSize: 5
    #最小的空闲连接数
    minIdle: 5
    #最大的空闲连接数
    maxIdle: 20
    #最大活动连接数
    maxActive: 20
    #从池中取连接的最大等待时间，单位ms.
    maxWait: 60000
    #每XXms运行一次空闲连接回收器
    timeBetweenEvictionRunsMillis: 60000
    #池中的连接空闲XX毫秒后被回收
    minEvictableIdleTimeMillis: 300000
    #验证使用的SQL语句
    validationQuery: SELECT 1 FROM DUAL
    #指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除.
    testWhileIdle: true
    #借出连接时不要测试，否则很影响性能
    testOnBorrow: false
    #归还连接时执行validationQuery检测连接是否有效，
    #    做了这个配置会降低性能
    testOnReturn: false
    #是否缓存preparedStatement，也就是PSCache。
    #  PSCache对支持游标的数据库性能提升巨大，比如说oracle。
    #  在mysql5.5以下的版本中没有PSCache功能，建议关闭掉。
    #  5.5及以上版本有PSCache，建议开启。
    poolPreparedStatements: true
    #属性类型是字符串，通过别名的方式配置扩展插件，
    #  常用的插件有：
    #  监控统计用的filter:stat
    #  日志用的filter:log4j
    #  防御sql注入的filter:wall
    filters: stat,wall,log4j
    #数据池连接参数
#    connectionProperties:
#      druid:
#        stat:
#          mergeSql: true
#          slowSqlMillis: 5000
###ThymeLeaf配置
  thymeleaf:
    #模板的模式，支持 HTML, XML TEXT JAVASCRIPT
    mode: HTML5
    #编码 可不用配置
    encoding: UTF-8
    #开发配置为false,避免修改模板还要重启服务器
    cache: false
    #配置模板路径，默认是templates，可以不用配置
    prefix: classpath:/templates
    #内容类别,可不用配置
    servlet:
      content-type: text/html
  #thymeleaf end
  #redis start
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 0
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 1000
  #redis end

#########log4j(这里可以不做指定  除非自己重新命名)##########
logging:
  config: classpath:log4j2.xml
  level:
    org:
      springframework: INFO

mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml



